---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
vars:
  region: "%{hiera('region')}"

  deployment_identifier: "%{hiera('deployment_identifier')}"

  bucket_name_prefix: "infrastructure-events"
  topic_name_prefix: "infrastructure-events"

  trusted_principals:
    - "099937559257"
    - "579878096224"
